romanz/trezor-agent

trezor_agent/trezor/_factory.py
TREZOR Connect does not ask for passphrase and always returns empty one.
I think we should do the same in trezor-agent. Otherwise the user has to enter passphrase twice everytime the agent is used. Passphrase can also create confusion for users unfamiliar of this concept.
=> don't ask for passphrase

trezor_agent/gpg/agent.py, trezor_agent/gpg/decode.py, trezor_agent/gpg/tests/test_decode.py
This handles unknown packets and supports more hashing algorithm.
The agent now uses TREZOR_GPG_USER_ID.
=> More robust gpg key parsing

setup.py, trezor_agent/factory.py, trezor_agent/gpg/keyring.py
=> better handling of keepkey dependency

README-GPG.md, trezor_agent/gpg/__main__.py, trezor_agent/gpg/agent.py, trezor_agent/gpg/decode.py, trezor_agent/gpg/encode.py, trezor_agent/gpg/keyring.py
Use the keygrip to find the correct public key instead of using environment variable.
=> gpg: replace TREZOR_GPG_USER_ID usage in gpg-agent mode

setup.py, trezor_agent/__main__.py, trezor_agent/client.py, trezor_agent/device/__init__.py, trezor_agent/device/interface.py, trezor_agent/device/keepkey.py, trezor_agent/device/ledger.py, trezor_agent/device/trezor.py, trezor_agent/gpg/__main__.py, trezor_agent/gpg/client.py, trezor_agent/protocol.py, trezor_agent/tests/test_client.py, trezor_agent/tests/test_protocol.py
This should allow using `trezor-agent` with minimal command-line configuration (see #75).
=> Allow loading multiple identities from a file (e.g. ~/.ssh/config)

trezor_agent/__main__.py
This is the error you get currently when trying to connect with mosh and specifying a login user:
```
$ trezor-agent -e ed25519 myuser@myhost --mosh -v
2016-12-14 23:53:05,770 INFO         identity #0: <ssh://myuser@myhost|ed25519>                                                       [__main__.py:144]
2016-12-14 23:53:06,332 INFO         running ['mosh', '-l', 'myuser', 'myhost'] with {'SSH_AUTH_SOCK': '/tmp/trezor-ssh-agent-hXtrRY', 'SSH_AGENT_PID': '16079'} [server.py:156]
Unknown option: l
Usage: /usr/bin/mosh [options] [--] [user@]host [command...]
--client=PATH        mosh client on local machine
(default: "mosh-client")
--server=COMMAND     mosh server on remote machine
(default: "mosh-server")
--predict=adaptive      local echo for slower links [default]
-a      --predict=always …
```
=> Mosh doesn't support "-l" for user, only user@host for args

trezor_agent/protocol.py, trezor_agent/tests/test_protocol.py
Fix Capistrano compatibility issue described at #99.
=> Allow contents in buffer when using _legacy_pubs

trezor_agent/__main__.py
Hi,
I ran into this connection error:
````
> trezor-agent  timothy@localhost
2017-04-10 00:22:01,818 ERROR        Connection error: open failed                                                                        [__main__.py:130]
````
I didn't know what was going on, whether there was a problem connecting to localhost or what. I eventually logged into trezor wallet and found that there too, my device was not recognized (probably because I did not unplug it/replug it after updating the HUD settigs.) Unplugging it and replugging it fixed everything.
=> Connection error is confusing

trezor_agent/__main__.py
This saves a lot of time when connecting to multiple hosts simultaneously (e.g., during a deploy) as every time we are asked to sign a challenge, all public keys are iterated to find the correct one. 
This can become especially slow when using the Bridge transport and/or many identities are defined.
=> Cache SSH public keys for the duration of the agent

trezor_agent/__main__.py, trezor_agent/client.py, trezor_agent/tests/test_client.py
This saves a lot of time on acquiring/releasing the device when many
identities are defined, especially when using the Bridge transport.
=> ssh: retrieve all keys using a single device session

libagent/ssh/client.py
The log contained `.__str__()` result (instead of `.to_string()`):
```
2017-10-05 18:11:56,170 INFO         please confirm user "git" login to \
"<libagent.device.interface.Identity object at 0x7f07e20e1a10>" using Trezor... [client.py:46]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/138)
=> ssh: fix identity stringification

README-GPG.md
I found your reddit post here https://www.reddit.com/r/TREZOR/comments/64k139/gpg_and_trezor_questions/dg6cwmc/?context=2 useful. But then when I needed the information again later, it took me a while to find it again. I think it would be useful to have in the readme, which this pull request does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/143)
=> README: Add a note about how to fetch a key's timestamp

doc/INSTALL.md
OpenSUSE users may have pip command pointing at pip3 and the installation will fail if they use default python dependencies which point to python2.
=> doc: Include python3 support in OpenSUSE instructions

libagent/gpg/__init__.py
Our agent should be invoked and re-used when running 'gpg --import'.
Fixes #165.
=> gpg: no need to remove the UNIX socket

doc/DESIGN.md
Start at documenting how the agent works and how/why it uses a hash to derive (instance specific) keys rather than use the primary key.
=> Some background and designn rationale for the use of derived keys

doc/README-SSH.md
Arch Linux uses systemd to manage the GPG and SSH agent by default, so I adapted that to use trezor-agent.  I didn't want the overhead of a process per terminal and I think process management is a bit simpler this way.
=> Add instructions for using SSH agent as systemd unit

README.md, doc/INSTALL.md, libagent/device/trezor.py, libagent/device/trezor_defs.py
Hello Roman,
this pull request introduces composite transport (implemented as TrezorDevice object), which can newly detect and connect to any Trezor device using various transports, including new Model T and even desktop emulator running over UDP.
TrezorDevice currently implements UDP transport (for emulator), Bridge transport (for any hardware), WebUSB transport (Model T) and HID transport (Trezor One).
Also, I modified installation instructions to use Python3, as Python2 is no longer officially maintained for python-trezor (although we'll accept pull requests fixing Python2 compatibility).
Also please note there's known bug in Model T for ed25519 (getpublickey returns invalid pubkey, which is correctly catched by trezor-agent). It will be fixed in upcoming firmware update.
Cheers!
Marek
=> trezor: Use composite transport

libagent/device/__init__.py, libagent/device/trezor.py, libagent/device/ui/__init__.py, libagent/device/ui/pinentry.py, libagent/device/ui/simple.py, libagent/gpg/__init__.py, libagent/gpg/agent.py, libagent/ssh/__init__.py
This should allow easier integration of custom PIN/passphrase entry tools (e.g. #202).
=> Refactor PIN/passphrase handling

doc/README-GPG.md, doc/README-SSH.md
This is mostly for consistency with the SSH agent usage.
I also changed the SSH agent systemd unit to add `Environment=` since I think it may be be necessary for the new pinentry stuff.
=> Add docs to show using the gpg agent with systemd; set PATH for ssh unit

doc/README-SSH.md, libagent/device/trezor.py, libagent/device/trezor_defs.py
Useful when you have multiple Trezors connected :)
I'm not sure if this is the best way to implement it, but it's probably the most straightforward one. Also this is a minority usecase.
=> trezor: use TREZOR_PATH environment variable to specify device path

agents/trezor/setup.py, libagent/device/fake_device.py, libagent/device/interface.py, libagent/device/trezor.py, libagent/device/trezor_defs.py, libagent/device/ui.py
resolves #277 
had to bump version requirement for python-trezor to 0.10.1 because otherwise the `[hidapi]` requirement would break. We could keep 0.9 compatibility if we could get around that. But there's probably no point in doing it.
We could *also* bump all the way to 0.11 and drop the compatibility wrappers
=> Trezor 0.11

README.md
As discussed [elsewhere](https://github.com/NixOS/nixpkgs/pull/69153#issuecomment-534952019), I was confused about the versioning of `libagent` and the individual agents for working with hardware devices.
Feel free to take this suggestion or not, as you see fit, but it attempts to clarify what we release based on the the source code in the repo.
=> Add components section

agents/trezor/setup.py, libagent/device/trezor.py, libagent/device/trezor_defs.py, libagent/device/ui.py
fixes #319 
also removes declared support for python < 3.5, which is not supported by trezorlib
not sure if you like how `ui.py` changes are handled?
i tried to keep the trezorlib import optional, but didn't want to go through `trezor_defs`
also on TT passphrase is automatically entered on device, unless envvar `TREZOR_PASSPHRASE` is set, which, again, I'm not sure if that is what you want.
the alternative might be something like:
* prompting before passphrase entry
* always prompt unless an envvar is set
* never prompt unless an envvar is set to prompt
* etc.?
=> support trezorlib 0.12

libagent/gpg/__init__.py
If the PATH contains spaces, the agent invocation script will break at runtime. This quotes the variable so that spaces don't break the script.
=> Quote PATH when writing agent invocation script

agents/trezor/setup.py, agents/trezor/trezor_agent.py, libagent/device/trezor.py, libagent/signify/__init__.py, setup.py
Following the discussion here: https://twitter.com/jb55/status/1151874791860629505.
Usage:
```
$ trezor-signify init JohnDoe
$ trezor-signify sign JohnDoe -m blob.txt
$ signify-openbsd -V -p JohnDoe.pub -m blob.txt
```
=> Support Signify-based signatures

doc/INSTALL.md
and redirecting to the root page for documentation.
I think this is the url to the intended documentation.
=> Udev rule configuration link was dead

libagent/gpg/__init__.py
=> Don't use sys.argv for device name parsing

agents/trezor/setup.py, agents/trezor/trezor_agent.py, libagent/age/__init__.py, libagent/age/client.py, libagent/device/trezor.py, libagent/device/trezor_defs.py, libagent/formats.py, setup.py, tox.ini
See https://github.com/str4d/rage/tree/main/age-plugin.
Example usage:
RAGE_DIR=$PWD/../Rust/rage
(cd $RAGE_DIR; cargo build --all)
export PATH=$PATH:$RAGE_DIR/target/debug
age-plugin-trezor -i "John Doe" | tee trezor.id
R=$(grep recipient trezor.id | cut -f 3 -d ' ')
date | tee msg.txt
rage -er $R < msg.txt > enc.txt
rage -di trezor.id < enc.txt
Requires latest `trezorlib` release: 
- https://github.com/trezor/trezor-firmware/pull/2004
- https://pypi.org/project/trezor/0.13.0/
=> Add `age` plugin support

libagent/formats.py, libagent/tests/test_formats.py
This should enable the usage of SSH-certificates using the NIST256 curve. By Testing this I found out that the payload to be signed is too big for the Trezor One but it is usable using a Trezor Model T.
This should also closes #372
=> Add Support for NIST256 ssh-certificates

README.md, agents/jade/jade_agent.py, agents/jade/setup.py, doc/DESIGN.md, doc/INSTALL.md, doc/README-GPG.md, doc/README-SSH.md, libagent/device/jade.py
Supports ssh and gpg, incl. ecdh/decryption.
Initially only supports curve 'nist256p1'.
=> Add support for the Blockstream Jade hww

libagent/ssh/protocol.py
Tried newest master, and with this addition it works with new ssh servers.
Without this PR it failed, because the function is being called with arg: `method(buf=buf)`.
Not sure if you have planned something else, in that case just close this pr.
=> fix: provide buf argument to unsupported_extension function

doc/README-SSH.md
This feature requires [OpenSSH 8.2](https://www.agwa.name/blog/post/ssh_signatures?s=09) and [Git 2.34](https://github.blog/2021-11-15-highlights-from-git-2-34/#tidbits) (from https://stackoverflow.com/a/45120525).
For more details, see the following great blog post: https://calebhearth.com/sign-git-with-ssh.
=> Document SSH-based Git signatures

libagent/formats.py, libagent/tests/test_formats.py
This should enable the usage of SSH-certificates using the ED25519 curve.
=> Add Support for ED25519 ssh-certificates

README.md
...as a supported device
If you can tell me the correct `jade_agent` URL on PyPi I can close #432 with this PR.
=> Update README to include Blockstream Jade

README.md, doc/README-Windows.md, libagent/age/__init__.py, libagent/device/ui.py, libagent/gpg/__init__.py, libagent/gpg/keyring.py, libagent/gpg/protocol.py, libagent/gpg/tests/test_keyring.py, libagent/server.py, libagent/ssh/__init__.py, libagent/ssh/protocol.py, libagent/util.py, libagent/win_server.py, setup.py, tox.ini
Builds on top of #362. Fixed parts that weren't working correctly, ensured it builds on Python 3.11 without errors, fixed issues with AGE, and added Windows-specific documentation.
Only thing missing is GPG support. However, I couldn't find a user-friendly non-CygWin GPG client for Windows. And I've never used GPG in the past. This makes it difficult to test, debug, or even just document GPG usage.
All other tools are confirmed to work, and appropriate Windows-specific tooling for them has been documented.
=> Fix Windows compatibility issues and AGE support

libagent/device/ui.py, libagent/ssh/__init__.py, libagent/win_server.py, setup.py, tox.ini
I am a novice in both Python and Windows Named Pipes but I did the best I could. A few notes:
* I only have a Trezor so I am not able to test the other devices, though the code should be agnostic to the device type anyway.
* I wasn't sure how to conditionally include packages in Python based on the platform (i.e. `pypiwin32`). Any ideas?
* There is no daemon support yet since it's a little more complicated on Windows. I left a TODO comment. I figured this could just come later.
* I had to change the public key temp file handling since the file was being deleted before it could be used on Windows. This currently leaves abandoned temp files so I'll need to revisit this. Thoughts?
* I haven't re-tested on Linux yet but it should still work (theoretically). I'll get around to it.
Should fix …
=> Add Windows native SSH support

.github/workflows/ci.yml
Ensures pending work loads on a pull request are cancelled if a new commit is pushed to it.
=> Add concurrency tag to CI

libagent/formats.py, libagent/ssh/client.py, libagent/tests/test_formats.py
Fixes #491.
Usage example:
```
$ trezor-agent -v 'SSH Certificate Authority' > /etc/ssh/trezor-ca.pub
$ echo 'TrustedUserCAKeys /etc/ssh/trezor-ca.pub' | sudo tee -a /etc/ssh/sshd_config
$ sudo systemctl restart ssh
$ ssh-keygen -t ed25519 -f user-key
$ trezor-agent -v 'SSH Certificate Authority' -- \
ssh-keygen -Us trezor-ca.pub -V '+10m' -I user-id -n user user-key.pub
...
Signed user key user-key-cert.pub: id "user-id" serial 0 for user valid from 2024-11-23T20:25:00 to 2024-11-23T20:36:27
```
Certification requires the following on-device approval:
```
ssh -v user@localhost -o CertificateFile=user-key-cert.pub -i user-key
...
debug1: Will attempt key: user-key-cert.pub ED25519-CERT SHA256:xdbgtQmUs5tUNf04f4Y3oQl5LGdBAMVjCH63R6EHH5Y explicit
debug1: Will attempt key: user-key ED25519 …
```
=> Support SSH CA generation

.github/workflows/ci.yml, agents/fake/setup.py, agents/jade/setup.py, agents/keepkey/setup.py, agents/ledger/setup.py, agents/onlykey/setup.py, agents/trezor/setup.py, libagent/age/__init__.py, libagent/gpg/__init__.py, libagent/ssh/__init__.py, setup.py
Python 3.12 has removed bundled `setuptools` (aka `pkg_resources`): https://docs.python.org/3.12/whatsnew/3.12.html#removed
Also bumps to python 3.8+ (since 3.7 is unsupported and would require a backport of `importlib.metadata`)
=> replace pkg_resources for python 3.12
