romanz/trezor-agent

README-GPG.md, README.md, trezor_agent/factory.py, trezor_agent/gpg/__main__.py, trezor_agent/gpg/decode.py, trezor_agent/gpg/keyring.py
=> Update ledger branch with the latest changes from master branch

trezor_agent/gpg/protocol.py
I'm not quite convinced that this is correct or enough.
What would suggest to test if this is correct?
I guess that decoding and encoding back should yield the original data, we could then run with a bunch keyrings. Could this be an interesting test(ing tool)?
=> Attempt at fixing issue #32

trezor_agent/gpg/agent.py
This should also enable revoking TREZOR-based GPG keys, effectively fixing #27 :)
=> Handle keyinfo request

README.md
This wasn't obvious to me at first. Please let me know if there is a better place to put it.
=> Add explanation about entering PIN

trezor_agent/gpg/agent.py, trezor_agent/gpg/device.py
=> Support more digests for GPG signatures

scripts/gpg-init, scripts/gpg-shell, setup.py, trezor_agent/gpg/__main__.py, trezor_agent/util.py
=> Auto spawn trezor-gpg-agent

trezor_agent/server.py, trezor_agent/tests/test_server.py
=> Concurrent handler

.travis.yml
(until https://github.com/keepkey/python-keepkey/issues/7 is resolved)
=> travis: install keepkey from GitHub

trezor_agent/device/trezor.py, trezor_agent/device/trezor_defs.py
See #107 for details.
For simplicity, I've used an environment variable for setting the required transport type.
=> Allow using TREZOR bridge (instead of HID transport)

libagent/ssh/__init__.py
=> Allow loading previously exported SSH public keys from a file

libagent/gpg/__init__.py, libagent/gpg/agent.py, libagent/gpg/client.py, scripts/gpg-init
This allows caching public keys (as done in the SSH agent).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/118)
=> Refactor GPG client usage at agent module

README-GPG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/132)
=> Fix link in README-GPG.md

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/133)
=> travis: fix setuptools issue

libagent/device/trezor.py, libagent/gpg/client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/140)
=> gpg: fix identity stringification

libagent/gpg/keyring.py
Following #139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/141)
=> gpg: support GnuPG 2.2.x default installation

libagent/gpg/encode.py, libagent/gpg/protocol.py
Following #145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/146)
=> Fix GPG default key preferences

libagent/device/keepkey_defs.py, libagent/device/trezor.py, libagent/device/trezor_defs.py
Otherwise, the next HID open() will fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/romanz/trezor-agent/151)
=> device: release HID handle before failing

doc/INSTALL.md
=> add documentation related to #155 to help other macOS/OSX users who are

libagent/gpg/__init__.py, libagent/gpg/keyring.py, libagent/util.py, setup.py
=> Persist PATH environment variable during GPG agent installation

.bumpversion.cfg, setup.py
=> Switch to bumpversion

libagent/gpg/__init__.py, libagent/ssh/__init__.py
=> Merge fixes from serge-name/trezor-agent

README.md, doc/INSTALL.md, doc/README-GPG.md, doc/README-SSH.md
=> Documentation changes

doc/README-GPG.md
Signed-off-by: Timothy Hobbs <timothyhobbs@seznam.cz>
=> Document the configuration of the git email setting and errors

libagent/device/ui.py, libagent/gpg/agent.py, libagent/gpg/keyring.py
=> Add simple symmetric encryption support for GPG

contrib/neopg-trezor, doc/README-NeoPG.md, libagent/gpg/__init__.py, libagent/gpg/agent.py, libagent/gpg/keyring.py, libagent/server.py
Works for Ed25519-based signatures: https://github.com/romanz/trezor-agent/commit/fa171e89235eba6e1540aaa779b35010f745cb4e
=> Add experimental support for NeoPG

libagent/device/ui.py, libagent/gpg/__init__.py, libagent/ssh/__init__.py
Broken since 2cb64991c3dc5530ccae8d239027a65fb3a001fd
Fix #284
=> Fix passphrase cache

doc/README-SSH.md
I spent many time figuring this out. Thought it would be a good idea to share.
=> Add example for rsync

libagent/device/keepkey_defs.py
The new KeepKey firmware uses WebUSB instead of HID
=> Fix detecting KeepKey USB device

libagent/ssh/client.py, libagent/ssh/protocol.py, libagent/ssh/tests/test_client.py
https://www.agwa.name/blog/post/ssh_signatures
See here for more details:
https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.sshsig
https://github.com/openssh/openssh-portable/blob/master/sshsig.c
https://github.com/openssh/openssh-portable/commit/2a9c9f7272c1e8665155118fe6536bebdafb6166
=> Support SSH signatures

setup.py
=> AGE support fix

doc/DESIGN.md
=> Fix a typo

libagent/ssh/client.py, libagent/ssh/protocol.py
See:
https://www.openssh.com/agent-restrict.html
https://github.com/openssh/openssh-portable/commit/266678e19eb0e86fdf865b431b6e172e7a95bf48
=> Don't fail if not all request is parsed

agents/jade/setup.py, libagent/device/jade.py
Update libagent requirement to the one that includes jade-agent.
=> Update setup.py for jade-agent

agents/jade/setup.py
=> Update Jade api version

libagent/age/__init__.py, tox.ini
https://github.com/FiloSottile/age/blob/v1.1.0-rc.1/internal/format/format.go#L45
=> Chunkify 'base64' format for age plugin

README.md, doc/README-GPG.md, doc/README-age.md
Following https://github.com/FiloSottile/age/releases/tag/v1.1.0 & https://github.com/FiloSottile/passage/commit/8128e011aac1359382f064cd26dc13928b3a17e8
=> age: add more documentation and examples

doc/README-SSH.md
document the ssh signatures examples
=> Update README-SSH.md with ssh signatures examples

libagent/device/ledger.py
- read app name / version
- if new version, handle new apdu format
=> ledger: handle 0.0.8 new apdu format

libagent/device/ledger.py
Small fix when the blob requires only 1 apdu, EOF byte wasnt set
=> ledger.py: fix EOF not always set

libagent/age/__init__.py
Following https://github.com/romanz/trezor-agent/issues/426.
=> Verify that 'identity-v1' state machine is used
